title: Makers All 
author: Anders Schneiderman
email: your-email@domain.com
description:  Makers All: Communities Shaping Their Destinies By Transforming Emerging Tech
url: https://makersall.org/

plugins:
  - jekyll-feed           # RSS feed for blog
  - jekyll-paginate       # Paginate the list of blog posts
# - jekyll-seo-tag

# Blogging setup
paginate: 5               # Number of posts to display at any one time

# Menu data for sitewide navigation
navigation_links:
  - name: About
    link: 'about/'
  - name: Blog	
    link: 'blog/'
  - name: Resources
    link: 'resources/'
